// <auto-generated />
using System;
using AdminConsole.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminConsole.Infrastructure.Migrations
{
    [DbContext(typeof(AdminConsoleDbContext))]
    [Migration("20260821152155_FixAppLogTimestampSqliteOrdering")]
    partial class FixAppLogTimestampSqliteOrdering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("AdminConsole.Domain.Models.AppLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AppLogEntries", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BackupMonitoringEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RdpMonitoringEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TelegramPrimaryAdminChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZabbixMonitoringEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.BackupCheckState", b =>
                {
                    b.Property<int>("BackupCheckStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveBadCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveUnknownCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastConfirmedOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastRawOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.HasKey("BackupCheckStateId");

                    b.HasIndex("Name", "Kind")
                        .IsUnique();

                    b.ToTable("BackupCheckStates", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.DowntimeRecord", b =>
                {
                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FellAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ClosedByMaintenance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RecoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ServerIp", "FellAt");

                    b.ToTable("DowntimeRecords", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.MaintenanceWindow", b =>
                {
                    b.Property<string>("WindowKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("WindowKey");

                    b.ToTable("MaintenanceWindows", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.StoredCredential", b =>
                {
                    b.Property<string>("Target")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProtectedSecret")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Target");

                    b.ToTable("StoredCredentials", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.TelegramAllowedUser", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("TelegramAllowedUsers", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Infrastructure.Data.Entities.MigrationMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MigrationMarker", (string)null);
                });

            modelBuilder.Entity("AdminConsole.Domain.Models.BackupCheckState", b =>
                {
                    b.OwnsMany("AdminConsole.Domain.Models.BackupSample", "History", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("BackupCheckStateId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset>("ObservedAt")
                                .HasColumnType("TEXT");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("BackupCheckStateId");

                            b1.ToTable("BackupSamples", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BackupCheckStateId");
                        });

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
